// Reads resources/normalization.json and resources/mcc_risk.json at build
// time and emits OUT_DIR/consts.rs with normalisation constants and a
// branchless `mcc_lookup` match. Avoids any I/O on the hot path.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

#[derive(serde::Deserialize)]
struct Normalization {
    max_amount: f32,
    max_installments: f32,
    amount_vs_avg_ratio: f32,
    max_minutes: f32,
    max_km: f32,
    max_tx_count_24h: f32,
    max_merchant_avg_amount: f32,
}

fn main() {
    let workspace_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    let resources = workspace_root.join("resources");
    let norm_path = resources.join("normalization.json");
    let mcc_path = resources.join("mcc_risk.json");

    println!("cargo:rerun-if-changed={}", norm_path.display());
    println!("cargo:rerun-if-changed={}", mcc_path.display());

    let norm: Normalization = serde_json::from_slice(&fs::read(&norm_path).unwrap()).unwrap();
    let mcc: BTreeMap<String, f32> = serde_json::from_slice(&fs::read(&mcc_path).unwrap()).unwrap();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut f = fs::File::create(out_dir.join("consts.rs")).unwrap();

    writeln!(f, "// generated by build.rs — do not edit").unwrap();
    writeln!(f, "pub const MAX_AMOUNT: f32 = {:?};", norm.max_amount).unwrap();
    writeln!(f, "pub const MAX_INSTALLMENTS: f32 = {:?};", norm.max_installments).unwrap();
    writeln!(f, "pub const AMOUNT_VS_AVG_RATIO: f32 = {:?};", norm.amount_vs_avg_ratio).unwrap();
    writeln!(f, "pub const MAX_MINUTES: f32 = {:?};", norm.max_minutes).unwrap();
    writeln!(f, "pub const MAX_KM: f32 = {:?};", norm.max_km).unwrap();
    writeln!(f, "pub const MAX_TX_COUNT_24H: f32 = {:?};", norm.max_tx_count_24h).unwrap();
    writeln!(f, "pub const MAX_MERCHANT_AVG_AMOUNT: f32 = {:?};", norm.max_merchant_avg_amount).unwrap();

    writeln!(f, "\n#[inline(always)]").unwrap();
    writeln!(f, "pub fn mcc_risk(mcc: &[u8]) -> f32 {{").unwrap();
    writeln!(f, "    match mcc {{").unwrap();
    for (k, v) in &mcc {
        writeln!(f, "        b{:?} => {:?},", k.as_str(), v).unwrap();
    }
    writeln!(f, "        _ => 0.5,").unwrap();
    writeln!(f, "    }}").unwrap();
    writeln!(f, "}}").unwrap();
}
